# https://moonrepo.dev/docs/config/workspace
$schema: 'https://moonrepo.dev/schemas/workspace.json'

projects:
  globs: []
  sources:
    root: '.'
    docs: 'docs'

defaultProject: 'root'

vcs:
  defaultBranch: 'main'
  provider: 'github'

pipeline:
  installDependencies: false
