name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      GOTOOLCHAIN: local
      MOON_TOOLCHAIN_FORCE_GLOBALS: 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup mise
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.6.14
          cache: false

      - name: Restore Go Caches
        id: go-cache-restore
        uses: actions/cache/restore@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: |
            ~/go
            ~/.cache/go-build
            ~/.cache/golangci-lint
          key: ${{ runner.os }}-go-moon-${{ hashFiles('mise.lock', 'go.mod', 'go.sum', '.golangci.yml') }}
          restore-keys: |
            ${{ runner.os }}-go-moon-

      - name: Run Moon CI
        run: moon ci --summary minimal

      - name: Run GoReleaser Check
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: v2.14.3
          args: check

      - name: Save Go Caches
        if: always() && github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.go-cache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/go
            ~/.cache/go-build
            ~/.cache/golangci-lint
          key: ${{ steps.go-cache-restore.outputs.cache-primary-key }}
